before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
  - format_overrides:
      - goos: windows
        format: zip
release:
  github:
  prerelease: auto
dockers:
  - image_templates:
      - "ghcr.io/rich7690/{{ .ProjectName }}:latest"
      - "ghcr.io/rich7690/{{ .ProjectName }}:{{ .Major }}"
      - "ghcr.io/rich7690/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/rich7690/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
